// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import * as dotenv from "dotenv"
import { defineConfig } from "prisma/config"

// .env und .env.local laden (Next.js-Standard), damit DATABASE_URL für prisma db push verfügbar ist
dotenv.config()
dotenv.config({ path: ".env.local", override: true })

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node prisma/seed.cjs",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
})
