export interface Country {
  id: string
  name: string
  continent: string
  code: string
  capital: string
  population: number
  area: number
  flag: string
  language: string
  currency: string
  currencySymbol: string
  coordinates: [number, number] // [latitude, longitude]
}

export const continents = [
  { id: "europe", name: "Europa", color: "#f59e0b" },
  { id: "asia", name: "Asien", color: "#ef4444" },
  { id: "africa", name: "Afrika", color: "#22c55e" },
  { id: "north-america", name: "Nordamerika", color: "#3b82f6" },
  { id: "south-america", name: "Südamerika", color: "#8b5cf6" },
  { id: "oceania", name: "Ozeanien", color: "#06b6d4" },
]

export const countries: Country[] = [
  // Europe
  {
    id: "de",
    name: "Deutschland",
    continent: "europe",
    code: "DE",
    capital: "Berlin",
    population: 83200000,
    area: 357386,
    flag: "🇩🇪",
    language: "Deutsch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [51.1657, 10.4515],
  },
  {
    id: "fr",
    name: "Frankreich",
    continent: "europe",
    code: "FR",
    capital: "Paris",
    population: 67390000,
    area: 640679,
    flag: "🇫🇷",
    language: "Französisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [46.2276, 2.2137],
  },
  {
    id: "it",
    name: "Italien",
    continent: "europe",
    code: "IT",
    capital: "Rom",
    population: 60360000,
    area: 301340,
    flag: "🇮🇹",
    language: "Italienisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [41.8719, 12.5674],
  },
  {
    id: "es",
    name: "Spanien",
    continent: "europe",
    code: "ES",
    capital: "Madrid",
    population: 47350000,
    area: 505990,
    flag: "🇪🇸",
    language: "Spanisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [40.4637, -3.7492],
  },
  {
    id: "pt",
    name: "Portugal",
    continent: "europe",
    code: "PT",
    capital: "Lissabon",
    population: 10300000,
    area: 92212,
    flag: "🇵🇹",
    language: "Portugiesisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [39.3999, -8.2245],
  },
  {
    id: "gb",
    name: "Vereinigtes Königreich",
    continent: "europe",
    code: "GB",
    capital: "London",
    population: 67220000,
    area: 242495,
    flag: "🇬🇧",
    language: "Englisch",
    currency: "Pfund Sterling",
    currencySymbol: "£",
    coordinates: [55.3781, -3.436],
  },
  {
    id: "nl",
    name: "Niederlande",
    continent: "europe",
    code: "NL",
    capital: "Amsterdam",
    population: 17440000,
    area: 41850,
    flag: "🇳🇱",
    language: "Niederländisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [52.1326, 5.2913],
  },
  {
    id: "be",
    name: "Belgien",
    continent: "europe",
    code: "BE",
    capital: "Brüssel",
    population: 11590000,
    area: 30528,
    flag: "🇧🇪",
    language: "Niederländisch/Französisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [50.5039, 4.4699],
  },
  {
    id: "at",
    name: "Österreich",
    continent: "europe",
    code: "AT",
    capital: "Wien",
    population: 9010000,
    area: 83879,
    flag: "🇦🇹",
    language: "Deutsch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [47.5162, 14.5501],
  },
  {
    id: "ch",
    name: "Schweiz",
    continent: "europe",
    code: "CH",
    capital: "Bern",
    population: 8670000,
    area: 41285,
    flag: "🇨🇭",
    language: "Deutsch/Französisch",
    currency: "Schweizer Franken",
    currencySymbol: "CHF",
    coordinates: [46.8182, 8.2275],
  },
  {
    id: "pl",
    name: "Polen",
    continent: "europe",
    code: "PL",
    capital: "Warschau",
    population: 37750000,
    area: 312696,
    flag: "🇵🇱",
    language: "Polnisch",
    currency: "Zloty",
    currencySymbol: "zł",
    coordinates: [51.9194, 19.1451],
  },
  {
    id: "cz",
    name: "Tschechien",
    continent: "europe",
    code: "CZ",
    capital: "Prag",
    population: 10700000,
    area: 78865,
    flag: "🇨🇿",
    language: "Tschechisch",
    currency: "Krone",
    currencySymbol: "Kč",
    coordinates: [49.8175, 15.473],
  },
  {
    id: "se",
    name: "Schweden",
    continent: "europe",
    code: "SE",
    capital: "Stockholm",
    population: 10350000,
    area: 450295,
    flag: "🇸🇪",
    language: "Schwedisch",
    currency: "Schwedische Krone",
    currencySymbol: "kr",
    coordinates: [60.1282, 18.6435],
  },
  {
    id: "no",
    name: "Norwegen",
    continent: "europe",
    code: "NO",
    capital: "Oslo",
    population: 5420000,
    area: 385207,
    flag: "🇳🇴",
    language: "Norwegisch",
    currency: "Norwegische Krone",
    currencySymbol: "kr",
    coordinates: [60.472, 8.4689],
  },
  {
    id: "dk",
    name: "Dänemark",
    continent: "europe",
    code: "DK",
    capital: "Kopenhagen",
    population: 5830000,
    area: 42933,
    flag: "🇩🇰",
    language: "Dänisch",
    currency: "Dänische Krone",
    currencySymbol: "kr",
    coordinates: [56.2639, 9.5018],
  },
  {
    id: "fi",
    name: "Finnland",
    continent: "europe",
    code: "FI",
    capital: "Helsinki",
    population: 5540000,
    area: 338424,
    flag: "🇫🇮",
    language: "Finnisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [61.9241, 25.7482],
  },
  {
    id: "ie",
    name: "Irland",
    continent: "europe",
    code: "IE",
    capital: "Dublin",
    population: 5010000,
    area: 70273,
    flag: "🇮🇪",
    language: "Englisch/Irisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [53.1424, -7.6921],
  },
  {
    id: "gr",
    name: "Griechenland",
    continent: "europe",
    code: "GR",
    capital: "Athen",
    population: 10420000,
    area: 131957,
    flag: "🇬🇷",
    language: "Griechisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [39.0742, 21.8243],
  },
  {
    id: "hr",
    name: "Kroatien",
    continent: "europe",
    code: "HR",
    capital: "Zagreb",
    population: 4050000,
    area: 56594,
    flag: "🇭🇷",
    language: "Kroatisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [45.1, 15.2],
  },
  {
    id: "hu",
    name: "Ungarn",
    continent: "europe",
    code: "HU",
    capital: "Budapest",
    population: 9660000,
    area: 93028,
    flag: "🇭🇺",
    language: "Ungarisch",
    currency: "Forint",
    currencySymbol: "Ft",
    coordinates: [47.1625, 19.5033],
  },
  {
    id: "ro",
    name: "Rumänien",
    continent: "europe",
    code: "RO",
    capital: "Bukarest",
    population: 19240000,
    area: 238391,
    flag: "🇷🇴",
    language: "Rumänisch",
    currency: "Leu",
    currencySymbol: "lei",
    coordinates: [45.9432, 24.9668],
  },
  {
    id: "bg",
    name: "Bulgarien",
    continent: "europe",
    code: "BG",
    capital: "Sofia",
    population: 6930000,
    area: 110879,
    flag: "🇧🇬",
    language: "Bulgarisch",
    currency: "Lew",
    currencySymbol: "лв",
    coordinates: [42.7339, 25.4858],
  },
  {
    id: "sk",
    name: "Slowakei",
    continent: "europe",
    code: "SK",
    capital: "Bratislava",
    population: 5460000,
    area: 49035,
    flag: "🇸🇰",
    language: "Slowakisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [48.669, 19.699],
  },
  {
    id: "si",
    name: "Slowenien",
    continent: "europe",
    code: "SI",
    capital: "Ljubljana",
    population: 2100000,
    area: 20273,
    flag: "🇸🇮",
    language: "Slowenisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [46.1512, 14.9955],
  },
  {
    id: "ee",
    name: "Estland",
    continent: "europe",
    code: "EE",
    capital: "Tallinn",
    population: 1330000,
    area: 45339,
    flag: "🇪🇪",
    language: "Estnisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [58.5953, 25.0136],
  },
  {
    id: "lv",
    name: "Lettland",
    continent: "europe",
    code: "LV",
    capital: "Riga",
    population: 1880000,
    area: 64559,
    flag: "🇱🇻",
    language: "Lettisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [56.8796, 24.6032],
  },
  {
    id: "lt",
    name: "Litauen",
    continent: "europe",
    code: "LT",
    capital: "Vilnius",
    population: 2790000,
    area: 65300,
    flag: "🇱🇹",
    language: "Litauisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [55.1694, 23.8813],
  },
  {
    id: "is",
    name: "Island",
    continent: "europe",
    code: "IS",
    capital: "Reykjavik",
    population: 370000,
    area: 103000,
    flag: "🇮🇸",
    language: "Isländisch",
    currency: "Isländische Krone",
    currencySymbol: "kr",
    coordinates: [64.9631, -19.0208],
  },
  {
    id: "lu",
    name: "Luxemburg",
    continent: "europe",
    code: "LU",
    capital: "Luxemburg",
    population: 640000,
    area: 2586,
    flag: "🇱🇺",
    language: "Luxemburgisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [49.8153, 6.1296],
  },
  {
    id: "mt",
    name: "Malta",
    continent: "europe",
    code: "MT",
    capital: "Valletta",
    population: 520000,
    area: 316,
    flag: "🇲🇹",
    language: "Maltesisch/Englisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [35.9375, 14.3754],
  },
  {
    id: "cy",
    name: "Zypern",
    continent: "europe",
    code: "CY",
    capital: "Nikosia",
    population: 1210000,
    area: 9251,
    flag: "🇨🇾",
    language: "Griechisch/Türkisch",
    currency: "Euro",
    currencySymbol: "€",
    coordinates: [35.1264, 33.4299],
  },
  {
    id: "rs",
    name: "Serbien",
    continent: "europe",
    code: "RS",
    capital: "Belgrad",
    population: 6910000,
    area: 88361,
    flag: "🇷🇸",
    language: "Serbisch",
    currency: "Dinar",
    currencySymbol: "дин",
    coordinates: [44.0165, 21.0059],
  },
  {
    id: "ua",
    name: "Ukraine",
    continent: "europe",
    code: "UA",
    capital: "Kiew",
    population: 44130000,
    area: 603500,
    flag: "🇺🇦",
    language: "Ukrainisch",
    currency: "Hrywnja",
    currencySymbol: "₴",
    coordinates: [48.3794, 31.1656],
  },
  {
    id: "tr",
    name: "Türkei",
    continent: "europe",
    code: "TR",
    capital: "Ankara",
    population: 84340000,
    area: 783356,
    flag: "🇹🇷",
    language: "Türkisch",
    currency: "Türkische Lira",
    currencySymbol: "₺",
    coordinates: [38.9637, 35.2433],
  },
  {
    id: "ru",
    name: "Russland",
    continent: "europe",
    code: "RU",
    capital: "Moskau",
    population: 146200000,
    area: 17098242,
    flag: "🇷🇺",
    language: "Russisch",
    currency: "Rubel",
    currencySymbol: "₽",
    coordinates: [61.524, 105.3188],
  },

  // Asia
  {
    id: "jp",
    name: "Japan",
    continent: "asia",
    code: "JP",
    capital: "Tokio",
    population: 126300000,
    area: 377975,
    flag: "🇯🇵",
    language: "Japanisch",
    currency: "Yen",
    currencySymbol: "¥",
    coordinates: [36.2048, 138.2529],
  },
  {
    id: "cn",
    name: "China",
    continent: "asia",
    code: "CN",
    capital: "Peking",
    population: 1412000000,
    area: 9596961,
    flag: "🇨🇳",
    language: "Chinesisch",
    currency: "Renminbi",
    currencySymbol: "¥",
    coordinates: [35.8617, 104.1954],
  },
  {
    id: "in",
    name: "Indien",
    continent: "asia",
    code: "IN",
    capital: "Neu-Delhi",
    population: 1380000000,
    area: 3287263,
    flag: "🇮🇳",
    language: "Hindi/Englisch",
    currency: "Rupie",
    currencySymbol: "₹",
    coordinates: [20.5937, 78.9629],
  },
  {
    id: "th",
    name: "Thailand",
    continent: "asia",
    code: "TH",
    capital: "Bangkok",
    population: 69950000,
    area: 513120,
    flag: "🇹🇭",
    language: "Thai",
    currency: "Baht",
    currencySymbol: "฿",
    coordinates: [15.87, 100.9925],
  },
  {
    id: "vn",
    name: "Vietnam",
    continent: "asia",
    code: "VN",
    capital: "Hanoi",
    population: 97340000,
    area: 331212,
    flag: "🇻🇳",
    language: "Vietnamesisch",
    currency: "Dong",
    currencySymbol: "₫",
    coordinates: [14.0583, 108.2772],
  },
  {
    id: "id",
    name: "Indonesien",
    continent: "asia",
    code: "ID",
    capital: "Jakarta",
    population: 273500000,
    area: 1904569,
    flag: "🇮🇩",
    language: "Indonesisch",
    currency: "Rupiah",
    currencySymbol: "Rp",
    coordinates: [-0.7893, 113.9213],
  },
  {
    id: "my",
    name: "Malaysia",
    continent: "asia",
    code: "MY",
    capital: "Kuala Lumpur",
    population: 32700000,
    area: 330803,
    flag: "🇲🇾",
    language: "Malaiisch",
    currency: "Ringgit",
    currencySymbol: "RM",
    coordinates: [4.2105, 101.9758],
  },
  {
    id: "sg",
    name: "Singapur",
    continent: "asia",
    code: "SG",
    capital: "Singapur",
    population: 5690000,
    area: 728,
    flag: "🇸🇬",
    language: "Englisch/Mandarin",
    currency: "Singapur-Dollar",
    currencySymbol: "S$",
    coordinates: [1.3521, 103.8198],
  },
  {
    id: "ph",
    name: "Philippinen",
    continent: "asia",
    code: "PH",
    capital: "Manila",
    population: 109600000,
    area: 300000,
    flag: "🇵🇭",
    language: "Filipino/Englisch",
    currency: "Peso",
    currencySymbol: "₱",
    coordinates: [12.8797, 121.774],
  },
  {
    id: "kr",
    name: "Südkorea",
    continent: "asia",
    code: "KR",
    capital: "Seoul",
    population: 51780000,
    area: 100210,
    flag: "🇰🇷",
    language: "Koreanisch",
    currency: "Won",
    currencySymbol: "₩",
    coordinates: [35.9078, 127.7669],
  },
  {
    id: "ae",
    name: "Vereinigte Arabische Emirate",
    continent: "asia",
    code: "AE",
    capital: "Abu Dhabi",
    population: 9890000,
    area: 83600,
    flag: "🇦🇪",
    language: "Arabisch",
    currency: "Dirham",
    currencySymbol: "د.إ",
    coordinates: [23.4241, 53.8478],
  },
  {
    id: "sa",
    name: "Saudi-Arabien",
    continent: "asia",
    code: "SA",
    capital: "Riad",
    population: 34810000,
    area: 2149690,
    flag: "🇸🇦",
    language: "Arabisch",
    currency: "Riyal",
    currencySymbol: "﷼",
    coordinates: [23.8859, 45.0792],
  },
  {
    id: "il",
    name: "Israel",
    continent: "asia",
    code: "IL",
    capital: "Jerusalem",
    population: 9220000,
    area: 20770,
    flag: "🇮🇱",
    language: "Hebräisch",
    currency: "Schekel",
    currencySymbol: "₪",
    coordinates: [31.0461, 34.8516],
  },
  {
    id: "jo",
    name: "Jordanien",
    continent: "asia",
    code: "JO",
    capital: "Amman",
    population: 10200000,
    area: 89342,
    flag: "🇯🇴",
    language: "Arabisch",
    currency: "Dinar",
    currencySymbol: "د.أ",
    coordinates: [30.5852, 36.2384],
  },
  {
    id: "np",
    name: "Nepal",
    continent: "asia",
    code: "NP",
    capital: "Kathmandu",
    population: 29140000,
    area: 147181,
    flag: "🇳🇵",
    language: "Nepalesisch",
    currency: "Rupie",
    currencySymbol: "₨",
    coordinates: [28.3949, 84.124],
  },
  {
    id: "lk",
    name: "Sri Lanka",
    continent: "asia",
    code: "LK",
    capital: "Sri Jayewardenepura Kotte",
    population: 21920000,
    area: 65610,
    flag: "🇱🇰",
    language: "Singhalesisch",
    currency: "Rupie",
    currencySymbol: "₨",
    coordinates: [7.8731, 80.7718],
  },
  {
    id: "kh",
    name: "Kambodscha",
    continent: "asia",
    code: "KH",
    capital: "Phnom Penh",
    population: 16720000,
    area: 181035,
    flag: "🇰🇭",
    language: "Khmer",
    currency: "Riel",
    currencySymbol: "៛",
    coordinates: [12.5657, 104.991],
  },
  {
    id: "mm",
    name: "Myanmar",
    continent: "asia",
    code: "MM",
    capital: "Naypyidaw",
    population: 54410000,
    area: 676578,
    flag: "🇲🇲",
    language: "Birmanisch",
    currency: "Kyat",
    currencySymbol: "K",
    coordinates: [21.9162, 95.956],
  },
  {
    id: "la",
    name: "Laos",
    continent: "asia",
    code: "LA",
    capital: "Vientiane",
    population: 7280000,
    area: 236800,
    flag: "🇱🇦",
    language: "Laotisch",
    currency: "Kip",
    currencySymbol: "₭",
    coordinates: [19.8563, 102.4955],
  },
  {
    id: "mn",
    name: "Mongolei",
    continent: "asia",
    code: "MN",
    capital: "Ulaanbaatar",
    population: 3280000,
    area: 1564116,
    flag: "🇲🇳",
    language: "Mongolisch",
    currency: "Tugrik",
    currencySymbol: "₮",
    coordinates: [46.8625, 103.8467],
  },
  {
    id: "bd",
    name: "Bangladesch",
    continent: "asia",
    code: "BD",
    capital: "Dhaka",
    population: 164690000,
    area: 147570,
    flag: "🇧🇩",
    language: "Bengali",
    currency: "Taka",
    currencySymbol: "৳",
    coordinates: [23.685, 90.3563],
  },
  {
    id: "pk",
    name: "Pakistan",
    continent: "asia",
    code: "PK",
    capital: "Islamabad",
    population: 220890000,
    area: 881913,
    flag: "🇵🇰",
    language: "Urdu/Englisch",
    currency: "Rupie",
    currencySymbol: "₨",
    coordinates: [30.3753, 69.3451],
  },

  // Africa
  {
    id: "za",
    name: "Südafrika",
    continent: "africa",
    code: "ZA",
    capital: "Pretoria",
    population: 59310000,
    area: 1221037,
    flag: "🇿🇦",
    language: "Englisch/Afrikaans",
    currency: "Rand",
    currencySymbol: "R",
    coordinates: [-30.5595, 22.9375],
  },
  {
    id: "eg",
    name: "Ägypten",
    continent: "africa",
    code: "EG",
    capital: "Kairo",
    population: 102300000,
    area: 1001450,
    flag: "🇪🇬",
    language: "Arabisch",
    currency: "Pfund",
    currencySymbol: "£",
    coordinates: [26.8206, 30.8025],
  },
  {
    id: "ma",
    name: "Marokko",
    continent: "africa",
    code: "MA",
    capital: "Rabat",
    population: 36910000,
    area: 446550,
    flag: "🇲🇦",
    language: "Arabisch",
    currency: "Dirham",
    currencySymbol: "د.م.",
    coordinates: [31.7917, -7.0926],
  },
  {
    id: "ke",
    name: "Kenia",
    continent: "africa",
    code: "KE",
    capital: "Nairobi",
    population: 53770000,
    area: 580367,
    flag: "🇰🇪",
    language: "Swahili/Englisch",
    currency: "Schilling",
    currencySymbol: "KSh",
    coordinates: [-0.0236, 37.9062],
  },
  {
    id: "tz",
    name: "Tansania",
    continent: "africa",
    code: "TZ",
    capital: "Dodoma",
    population: 59730000,
    area: 947303,
    flag: "🇹🇿",
    language: "Swahili/Englisch",
    currency: "Schilling",
    currencySymbol: "TSh",
    coordinates: [-6.369, 34.8888],
  },
  {
    id: "ng",
    name: "Nigeria",
    continent: "africa",
    code: "NG",
    capital: "Abuja",
    population: 206140000,
    area: 923768,
    flag: "🇳🇬",
    language: "Englisch",
    currency: "Naira",
    currencySymbol: "₦",
    coordinates: [9.082, 8.6753],
  },
  {
    id: "gh",
    name: "Ghana",
    continent: "africa",
    code: "GH",
    capital: "Accra",
    population: 31070000,
    area: 238533,
    flag: "🇬🇭",
    language: "Englisch",
    currency: "Cedi",
    currencySymbol: "₵",
    coordinates: [7.9465, -1.0232],
  },
  {
    id: "et",
    name: "Äthiopien",
    continent: "africa",
    code: "ET",
    capital: "Addis Abeba",
    population: 115000000,
    area: 1104300,
    flag: "🇪🇹",
    language: "Amharisch",
    currency: "Birr",
    currencySymbol: "Br",
    coordinates: [9.145, 40.4897],
  },
  {
    id: "tn",
    name: "Tunesien",
    continent: "africa",
    code: "TN",
    capital: "Tunis",
    population: 11820000,
    area: 163610,
    flag: "🇹🇳",
    language: "Arabisch",
    currency: "Dinar",
    currencySymbol: "د.ت",
    coordinates: [33.8869, 9.5375],
  },
  {
    id: "sn",
    name: "Senegal",
    continent: "africa",
    code: "SN",
    capital: "Dakar",
    population: 16740000,
    area: 196722,
    flag: "🇸🇳",
    language: "Französisch",
    currency: "CFA-Franc",
    currencySymbol: "CFA",
    coordinates: [14.4974, -14.4524],
  },
  {
    id: "rw",
    name: "Ruanda",
    continent: "africa",
    code: "RW",
    capital: "Kigali",
    population: 12950000,
    area: 26338,
    flag: "🇷🇼",
    language: "Englisch/Französisch",
    currency: "Franc",
    currencySymbol: "FRw",
    coordinates: [-1.9403, 29.8739],
  },
  {
    id: "ug",
    name: "Uganda",
    continent: "africa",
    code: "UG",
    capital: "Kampala",
    population: 45740000,
    area: 241550,
    flag: "🇺🇬",
    language: "Englisch/Swahili",
    currency: "Schilling",
    currencySymbol: "USh",
    coordinates: [1.3733, 32.2903],
  },
  {
    id: "na",
    name: "Namibia",
    continent: "africa",
    code: "NA",
    capital: "Windhoek",
    population: 2540000,
    area: 825615,
    flag: "🇳🇦",
    language: "Englisch",
    currency: "Dollar",
    currencySymbol: "N$",
    coordinates: [-22.9576, 18.4904],
  },
  {
    id: "bw",
    name: "Botswana",
    continent: "africa",
    code: "BW",
    capital: "Gaborone",
    population: 2350000,
    area: 581730,
    flag: "🇧🇼",
    language: "Englisch",
    currency: "Pula",
    currencySymbol: "P",
    coordinates: [-22.3285, 24.6849],
  },
  {
    id: "mu",
    name: "Mauritius",
    continent: "africa",
    code: "MU",
    capital: "Port Louis",
    population: 1270000,
    area: 2040,
    flag: "🇲🇺",
    language: "Englisch/Französisch",
    currency: "Rupie",
    currencySymbol: "₨",
    coordinates: [-20.3484, 57.5522],
  },

  // North America
  {
    id: "us",
    name: "Vereinigte Staaten",
    continent: "north-america",
    code: "US",
    capital: "Washington D.C.",
    population: 331000000,
    area: 9833520,
    flag: "🇺🇸",
    language: "Englisch",
    currency: "Dollar",
    currencySymbol: "$",
    coordinates: [37.0902, -95.7129],
  },
  {
    id: "ca",
    name: "Kanada",
    continent: "north-america",
    code: "CA",
    capital: "Ottawa",
    population: 38010000,
    area: 9984670,
    flag: "🇨🇦",
    language: "Englisch/Französisch",
    currency: "Dollar",
    currencySymbol: "CA$",
    coordinates: [56.1304, -106.3468],
  },
  {
    id: "mx",
    name: "Mexiko",
    continent: "north-america",
    code: "MX",
    capital: "Mexiko-Stadt",
    population: 128900000,
    area: 1964375,
    flag: "🇲🇽",
    language: "Spanisch",
    currency: "Peso",
    currencySymbol: "$",
    coordinates: [23.6345, -102.5528],
  },
  {
    id: "cu",
    name: "Kuba",
    continent: "north-america",
    code: "CU",
    capital: "Havanna",
    population: 11330000,
    area: 109884,
    flag: "🇨🇺",
    language: "Spanisch",
    currency: "Peso",
    currencySymbol: "$",
    coordinates: [21.5218, -77.7812],
  },
  {
    id: "jm",
    name: "Jamaika",
    continent: "north-america",
    code: "JM",
    capital: "Kingston",
    population: 2960000,
    area: 10991,
    flag: "🇯🇲",
    language: "Englisch",
    currency: "Dollar",
    currencySymbol: "J$",
    coordinates: [18.1096, -77.2975],
  },
  {
    id: "do",
    name: "Dominikanische Republik",
    continent: "north-america",
    code: "DO",
    capital: "Santo Domingo",
    population: 10850000,
    area: 48671,
    flag: "🇩🇴",
    language: "Spanisch",
    currency: "Peso",
    currencySymbol: "RD$",
    coordinates: [18.7357, -70.1627],
  },
  {
    id: "cr",
    name: "Costa Rica",
    continent: "north-america",
    code: "CR",
    capital: "San José",
    population: 5090000,
    area: 51100,
    flag: "🇨🇷",
    language: "Spanisch",
    currency: "Colón",
    currencySymbol: "₡",
    coordinates: [9.7489, -83.7534],
  },
  {
    id: "pa",
    name: "Panama",
    continent: "north-america",
    code: "PA",
    capital: "Panama-Stadt",
    population: 4310000,
    area: 75417,
    flag: "🇵🇦",
    language: "Spanisch",
    currency: "Balboa",
    currencySymbol: "B/.",
    coordinates: [8.538, -80.7821],
  },
  {
    id: "gt",
    name: "Guatemala",
    continent: "north-america",
    code: "GT",
    capital: "Guatemala-Stadt",
    population: 16860000,
    area: 108889,
    flag: "🇬🇹",
    language: "Spanisch",
    currency: "Quetzal",
    currencySymbol: "Q",
    coordinates: [15.7835, -90.2308],
  },
  {
    id: "bs",
    name: "Bahamas",
    continent: "north-america",
    code: "BS",
    capital: "Nassau",
    population: 390000,
    area: 13943,
    flag: "🇧🇸",
    language: "Englisch",
    currency: "Dollar",
    currencySymbol: "B$",
    coordinates: [25.0343, -77.3963],
  },

  // South America
  {
    id: "br",
    name: "Brasilien",
    continent: "south-america",
    code: "BR",
    capital: "Brasília",
    population: 212600000,
    area: 8515767,
    flag: "🇧🇷",
    language: "Portugiesisch",
    currency: "Real",
    currencySymbol: "R$",
    coordinates: [-14.235, -51.9253],
  },
  {
    id: "ar",
    name: "Argentinien",
    continent: "south-america",
    code: "AR",
    capital: "Buenos Aires",
    population: 45380000,
    area: 2780400,
    flag: "🇦🇷",
    language: "Spanisch",
    currency: "Peso",
    currencySymbol: "$",
    coordinates: [-38.4161, -63.6167],
  },
  {
    id: "cl",
    name: "Chile",
    continent: "south-america",
    code: "CL",
    capital: "Santiago",
    population: 19120000,
    area: 756102,
    flag: "🇨🇱",
    language: "Spanisch",
    currency: "Peso",
    currencySymbol: "$",
    coordinates: [-35.6751, -71.543],
  },
  {
    id: "pe",
    name: "Peru",
    continent: "south-america",
    code: "PE",
    capital: "Lima",
    population: 32970000,
    area: 1285216,
    flag: "🇵🇪",
    language: "Spanisch",
    currency: "Sol",
    currencySymbol: "S/",
    coordinates: [-9.19, -75.0152],
  },
  {
    id: "co",
    name: "Kolumbien",
    continent: "south-america",
    code: "CO",
    capital: "Bogotá",
    population: 50880000,
    area: 1141748,
    flag: "🇨🇴",
    language: "Spanisch",
    currency: "Peso",
    currencySymbol: "$",
    coordinates: [4.5709, -74.2973],
  },
  {
    id: "ec",
    name: "Ecuador",
    continent: "south-america",
    code: "EC",
    capital: "Quito",
    population: 17640000,
    area: 276841,
    flag: "🇪🇨",
    language: "Spanisch",
    currency: "US-Dollar",
    currencySymbol: "$",
    coordinates: [-1.8312, -78.1834],
  },
  {
    id: "bo",
    name: "Bolivien",
    continent: "south-america",
    code: "BO",
    capital: "Sucre",
    population: 11670000,
    area: 1098581,
    flag: "🇧🇴",
    language: "Spanisch",
    currency: "Boliviano",
    currencySymbol: "Bs",
    coordinates: [-16.2902, -63.5887],
  },
  {
    id: "uy",
    name: "Uruguay",
    continent: "south-america",
    code: "UY",
    capital: "Montevideo",
    population: 3470000,
    area: 176215,
    flag: "🇺🇾",
    language: "Spanisch",
    currency: "Peso",
    currencySymbol: "$U",
    coordinates: [-32.5228, -55.7658],
  },
  {
    id: "py",
    name: "Paraguay",
    continent: "south-america",
    code: "PY",
    capital: "Asunción",
    population: 7130000,
    area: 406752,
    flag: "🇵🇾",
    language: "Spanisch/Guarani",
    currency: "Guaraní",
    currencySymbol: "₲",
    coordinates: [-23.4425, -58.4438],
  },
  {
    id: "ve",
    name: "Venezuela",
    continent: "south-america",
    code: "VE",
    capital: "Caracas",
    population: 28440000,
    area: 916445,
    flag: "🇻🇪",
    language: "Spanisch",
    currency: "Bolívar",
    currencySymbol: "Bs",
    coordinates: [6.4238, -66.5897],
  },

  // Oceania
  {
    id: "au",
    name: "Australien",
    continent: "oceania",
    code: "AU",
    capital: "Canberra",
    population: 25690000,
    area: 7692024,
    flag: "🇦🇺",
    language: "Englisch",
    currency: "Dollar",
    currencySymbol: "A$",
    coordinates: [-25.2744, 133.7751],
  },
  {
    id: "nz",
    name: "Neuseeland",
    continent: "oceania",
    code: "NZ",
    capital: "Wellington",
    population: 5080000,
    area: 268021,
    flag: "🇳🇿",
    language: "Englisch",
    currency: "Dollar",
    currencySymbol: "NZ$",
    coordinates: [-40.9006, 174.886],
  },
  {
    id: "fj",
    name: "Fidschi",
    continent: "oceania",
    code: "FJ",
    capital: "Suva",
    population: 896000,
    area: 18274,
    flag: "🇫🇯",
    language: "Englisch/Fidschianisch",
    currency: "Dollar",
    currencySymbol: "FJ$",
    coordinates: [-17.7134, 178.065],
  },
  {
    id: "pg",
    name: "Papua-Neuguinea",
    continent: "oceania",
    code: "PG",
    capital: "Port Moresby",
    population: 8940000,
    area: 462840,
    flag: "🇵🇬",
    language: "Englisch",
    currency: "Kina",
    currencySymbol: "K",
    coordinates: [-6.315, 143.9555],
  },
  {
    id: "ws",
    name: "Samoa",
    continent: "oceania",
    code: "WS",
    capital: "Apia",
    population: 198000,
    area: 2842,
    flag: "🇼🇸",
    language: "Samoanisch/Englisch",
    currency: "Tala",
    currencySymbol: "WS$",
    coordinates: [-13.759, -172.1046],
  },
  {
    id: "to",
    name: "Tonga",
    continent: "oceania",
    code: "TO",
    capital: "Nukuʻalofa",
    population: 105000,
    area: 747,
    flag: "🇹🇴",
    language: "Tongaisch/Englisch",
    currency: "Paʻanga",
    currencySymbol: "T$",
    coordinates: [-21.179, -175.1982],
  },
  {
    id: "vu",
    name: "Vanuatu",
    continent: "oceania",
    code: "VU",
    capital: "Port Vila",
    population: 307000,
    area: 12189,
    flag: "🇻🇺",
    language: "Bislama/Englisch",
    currency: "Vatu",
    currencySymbol: "VT",
    coordinates: [-15.3767, 166.9592],
  },
]

export interface Achievement {
  id: string
  name: string
  description: string
  icon: string
  requirement: number
  continent?: string
}

export const achievements: Achievement[] = [
  {
    id: "first-stamp",
    name: "Erster Stempel",
    description: "Besuche dein erstes Land",
    icon: "🎫",
    requirement: 1,
  },
  {
    id: "explorer",
    name: "Entdecker",
    description: "Besuche 5 Länder",
    icon: "🧭",
    requirement: 5,
  },
  {
    id: "globetrotter",
    name: "Globetrotter",
    description: "Besuche 10 Länder",
    icon: "🌍",
    requirement: 10,
  },
  {
    id: "world-traveler",
    name: "Weltreisender",
    description: "Besuche 25 Länder",
    icon: "✈️",
    requirement: 25,
  },
  {
    id: "adventurer",
    name: "Abenteurer",
    description: "Besuche 50 Länder",
    icon: "🎒",
    requirement: 50,
  },
  {
    id: "legend",
    name: "Legende",
    description: "Besuche 100 Länder",
    icon: "👑",
    requirement: 100,
  },
  {
    id: "europe-starter",
    name: "Europa-Starter",
    description: "Besuche 5 europäische Länder",
    icon: "🇪🇺",
    requirement: 5,
    continent: "europe",
  },
  {
    id: "europe-master",
    name: "Europa-Meister",
    description: "Besuche 15 europäische Länder",
    icon: "🏰",
    requirement: 15,
    continent: "europe",
  },
  {
    id: "asia-explorer",
    name: "Asien-Entdecker",
    description: "Besuche 5 asiatische Länder",
    icon: "🏯",
    requirement: 5,
    continent: "asia",
  },
  {
    id: "africa-adventurer",
    name: "Afrika-Abenteurer",
    description: "Besuche 3 afrikanische Länder",
    icon: "🦁",
    requirement: 3,
    continent: "africa",
  },
]

export const alpha3ToCountryId: Record<string, string> = {
  // Europe
  DEU: "de",
  FRA: "fr",
  ITA: "it",
  ESP: "es",
  PRT: "pt",
  GBR: "gb",
  NLD: "nl",
  BEL: "be",
  AUT: "at",
  CHE: "ch",
  POL: "pl",
  CZE: "cz",
  SWE: "se",
  NOR: "no",
  DNK: "dk",
  FIN: "fi",
  IRL: "ie",
  GRC: "gr",
  HRV: "hr",
  HUN: "hu",
  ROU: "ro",
  BGR: "bg",
  SVK: "sk",
  SVN: "si",
  EST: "ee",
  LVA: "lv",
  LTU: "lt",
  ISL: "is",
  LUX: "lu",
  MLT: "mt",
  CYP: "cy",
  SRB: "rs",
  UKR: "ua",
  TUR: "tr",
  RUS: "ru",
  // Asia
  JPN: "jp",
  CHN: "cn",
  IND: "in",
  THA: "th",
  VNM: "vn",
  IDN: "id",
  MYS: "my",
  SGP: "sg",
  PHL: "ph",
  KOR: "kr",
  ARE: "ae",
  SAU: "sa",
  ISR: "il",
  JOR: "jo",
  NPL: "np",
  LKA: "lk",
  KHM: "kh",
  MMR: "mm",
  LAO: "la",
  MNG: "mn",
  BGD: "bd",
  PAK: "pk",
  // Africa
  ZAF: "za",
  EGY: "eg",
  MAR: "ma",
  KEN: "ke",
  TZA: "tz",
  NGA: "ng",
  GHA: "gh",
  ETH: "et",
  TUN: "tn",
  SEN: "sn",
  RWA: "rw",
  UGA: "ug",
  NAM: "na",
  BWA: "bw",
  MUS: "mu",
  // North America
  USA: "us",
  CAN: "ca",
  MEX: "mx",
  CUB: "cu",
  JAM: "jm",
  DOM: "do",
  CRI: "cr",
  PAN: "pa",
  GTM: "gt",
  BHS: "bs",
  // South America
  BRA: "br",
  ARG: "ar",
  CHL: "cl",
  PER: "pe",
  COL: "co",
  ECU: "ec",
  BOL: "bo",
  URY: "uy",
  PRY: "py",
  VEN: "ve",
  // Oceania
  AUS: "au",
  NZL: "nz",
  FJI: "fj",
  PNG: "pg",
  WSM: "ws",
  TON: "to",
  VUT: "vu",
}
